[package]
name = "circom_error"
version = "2.0.0"
edition = "2021"
homepage = "https://docs.circom.io/"
license = "GPL-3.0-only"
repository = "https://github.com/iden3/circom"

[dependencies]
codespan = "0.11"
codespan-reporting = "0.11"
