[package]
name = "code_producers"
version = "2.0.1"
authors = ["hermeGarcia <hermegarcianavarro@gmail.com>"]
edition = "2021"

[dependencies]
handlebars = "4"
lz_fnv = "0.1"
num-bigint-dig = "0.8"
serde_json = "1"
