[package]
name = "circom_algebra"
version = "2.0.0"
authors = ["hermeGarcia <hermegarcianavarro@gmail.com>"]
edition = "2021"

[dependencies]
num-bigint-dig = "0.6.0"
num-traits = "0.2.6"

# Internal
constant_tracking = { path = "../constant_tracking" }
