[package]
name = "circom_algebra"
version = "2.0.0"
authors = ["hermeGarcia <hermegarcianavarro@gmail.com>"]
edition = "2021"

[dependencies]
num-bigint-dig = "0.8"
num-traits = "0.2"

# Internal
circom_constant_tracking = { path = "../circom_constant_tracking" }
