[package]
name = "circom_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint-dig = "0.6.0"
circom_error = { path = "../circom_error" }
serde = "1.0.82"
serde_derive = "1.0.91"
